/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Calendario': RouteRecordInfo<'/Calendario', '/Calendario', Record<never, never>, Record<never, never>>,
    '/Encuesta1': RouteRecordInfo<'/Encuesta1', '/Encuesta1', Record<never, never>, Record<never, never>>,
    '/Encuesta2': RouteRecordInfo<'/Encuesta2', '/Encuesta2', Record<never, never>, Record<never, never>>,
    '/Inicio': RouteRecordInfo<'/Inicio', '/Inicio', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/PanelProfesorado': RouteRecordInfo<'/PanelProfesorado', '/PanelProfesorado', Record<never, never>, Record<never, never>>,
  }
}
