name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Puedes cambiar la versión de Node.js según tus necesidades

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Set up Git
      run: |
        git config --global user.email "lr33908@gmail.com"
        git config --global user.name "lauraRodriguezSedeno"


    - name: Deploy to gh-pages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git checkout -b gh-pages || true
        shopt -s extglob # Habilitar coincidencias de patrones extendidos
        rm -rf !("docs") # Borrar todo excepto la carpeta 'docs'
        mv -f docs/* .
        rm -rf docs # Borrar la carpeta 'docs' (si está vacía)
        git add .
        git commit -m "Deploy to gh-pages"
         git push --force --quiet "https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
